### ISSUE TITLE
Why EM and F1 are lower than official results?

### ISSUE THREAD

**Issue by sharejing** [galsang/BiDAF-pytorch#1]
Hi, galsang. Nice work! But I want to know why EM and F1 are lower than official results. Have you analyzed it? Thanks!

**Comment by galsang** [comment]
I don't know the exact reason, but there are some possible candidates.
A possible one is the different initialization of the weights, which can be a big impact in real.

**Comment by sharejing** [comment]
Hi, galsang. I think so.  
I prefer to Pytorch, and  I have been doing things on reading comprehension. Thank you for your reply!

**Comment by zhiqihuang** [comment]
I suspect that the paper results are based on GloVe 300d. And the lower results are from GloVe 100d. Just a guess.
