### ISSUE TITLE
Some questions about the implementation in package utils

### ISSUE THREAD

**Issue by SparkJiao** [galsang/BiDAF-pytorch#2]
Hi!
I'm a beginner of pytorch and deep learning and now I'm considering implementing the bidaf model by myself and I think your code is so clean! I love it so much!
So I still don't know why we need to re-implement the linear module and the lstm layer by ourself? Are the models implemented in the torch.nn module not better enough? Or it's convenient to modified the hyper-parameter?
Thanks u a lot!

**Comment by galsang** [comment]
Actually they are just a kind of thin wrappers which facilitate consistent initialization settings and some customized variations, for some frequently re-used modules (e.g. linear, LSTM cell, and so on) in the code.
For instance, the newly defined **Linear** module is equivalent to the original **nn.Linear** but its initialization scheme is somewhat different. 
I hope this answer would help.

**Comment by SparkJiao** [comment]
That's great. I've got it. Thank u a lot!
