### ISSUE TITLE
Some confusions about Contextual Embedding Layer?

### ISSUE THREAD

**Issue by IrvingBei** [galsang/BiDAF-pytorch#20]
Hi, thanks for your sharing this reproduction code firstly, I am a little confused about the Contextual Embedding Layer. Are there two ways for Contextual embedding? one way is using the same BiLSTM for both passage and question, the other way is using the different BiLSTMs for passage and question. and you employ the first way, using the same BiLSTM, is it right?

**Comment by galsang** [comment]
Right. As far as I know, the same parameters are used for both context and question in most cases, due to learning efficiency (e.g., the efficiency in terms of the number of parameters).

**Comment by IrvingBei** [comment]
ok, that's true in most cases, thanks again!
