### ISSUE TITLE
ntlk错误

### ISSUE THREAD

**Issue by Backlight-SS** [galsang/BiDAF-pytorch#3]
*********************************************************************
  Resource 'tokenizers/punkt/PY3/english.pickle' not found.
  Please use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()
  Searched in:
    - '/home/sunshen/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
我是远程连接服务器，请问怎么解决这个问题

**Comment by galsang** [comment]
You’d better use English when talking to the non-Chinese.
Search on google about how to install pickle.

**Comment by Backlight-SS** [comment]
Sorry, Python 2.7 and Python 3.4 include the pickle and cPickle modules already,
so,why install pickle?

**Comment by Charrnander** [comment]
> Sorry, Python 2.7 and Python 3.4 include the pickle and cPickle modules already,
> so,why install pickle?

You need to use NLTK Downloader to download the file named 'english.pickle'
