### ISSUE TITLE
Predictor?

### ISSUE THREAD

**Issue by ken-the-lin** [galsang/BiDAF-pytorch#5]
Thank you for your nice implementation. The training went well.
I have been trying to build a predictor using your model, but I have been encountering a series of problems unresolvable for me.

Can you make a predictor out of your current code, to achieve something like
answer = predictor(context, question)

Thanks in advance

**Comment by galsang** [comment]
You mean some kind of an interactive version of the code which can accept a sentence at a time?
Yeah, it's possible and I'll keep in mind appending the feature but I'm not sure when this would be done.
