### ISSUE TITLE
why change char_dim and word_len dimesion and then use conv2d

### ISSUE THREAD

**Issue by VectorChanger0** [galsang/BiDAF-pytorch#6]
around line 82~88 in model.py
_# (batch * seq_len, 1, char_dim, word_len)_
`x = x.view(-1, self.args.char_dim, x.size(2)).unsqueeze(1)`
 _# (batch * seq_len, char_channel_size, 1, conv_len) -> (batch * seq_len, char_channel_size, conv_len)_
`            x = self.char_conv(x).squeeze()`
why need change the dims first ? Why not directly use conv1D ?

**Comment by galsang** [comment]
There's no reason for using conv2D instead of conv1D...
You can, of course, use conv1D if you want.
