### ISSUE TITLE
Cuda out of memory will fix when pytorch update to 1.0 

### ISSUE THREAD

**Issue by BITLsy** [galsang/BiDAF-pytorch#7]
Thanks for your code, very clear!
When i first clone the code and run in my gtx 1060 6G GPU, it exploded soon. I try to delect some intermediate variable in the Bidaf model, but have no effect. Finally, update pytorch to 1.0 version and run again, Nvidia-smi show only about 4G GPU memory be used, even add up the train_batch_size to 128.
So cool !

**Comment by galsang** [comment]
How nice it is! Thanks for your test.

**Comment by dominikabasaj** [comment]
Hi, it did not work for me though - did you do any additional changes to the code? I have GPU 1070 8 gb.

**Comment by BITLsy** [comment]
@dominikabasaj I add code in train and test iterator 
```
del batch
if i % 100 == 0:
    gc.collect()
```
but I don't know whether it work or not
