### ISSUE TITLE
Why not use PyTorch LSTM and Linear

### ISSUE THREAD

**Issue by jwang-lp** [galsang/BiDAF-pytorch#8]
Hi Taeuk! Thank you for implementing BiDAF in such an elegant way! Why do you use your version of LSTM and linear in utils.nn instead of using the PyTorch LSTM and linear?

**Comment by jwang-lp** [comment]
Oh! I see! You wrote some wrappers for these two functions!

**Comment by kushalj001** [comment]
@jwang-lp  @galsang Does the initialization in your wrappers affect the results drastically?
