### ISSUE TITLE
Error:RawField object has no attribute 'is_target'

### ISSUE THREAD

**Issue by RAddRiceee** [galsang/BiDAF-pytorch#9]
Thanks for your sharing, your code is readable!  when i cloned the project to run ,i got this problem" the 
 RawField object has no attribute 'is_target" .But I m a noob ,can you tell me what may be the problem?
Thank you!

**Comment by galsang** [comment]
It looks like the problem is related to the version compatibility of the **Torchtext** library utilized in our code. You can try using the lastest version of the library or the version specified in the README.md. I expect one of the two will work fine.

**Comment by RAddRiceee** [comment]
> It looks like the problem is related to the version compatibility of the **Torchtext** library utilized in our code. You can try using the lastest version of the library or the version specified in the README.md. I expect one of the two will work fine.
thank you for your reply.I will have a try right now

**Comment by shbupt** [comment]
I added `self.RAW.is_target = `False` `  to solve this problem.

**Comment by Shawn617** [comment]
> I added `self.RAW.is_target = `False` ` to solve this problem.

Where do you add this line of code?

**Comment by galsang** [comment]
See the [latest commit](https://github.com/galsang/BiDAF-pytorch/commit/c4e3640fb4df5acbcc28c256c043441ab6cbdbf7).
